
name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Menjalankan workflow setiap kali ada push ke branch main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t username/kutubu_e-commerce:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push username/kutubu_e-commerce:latest
